[module.hugoVersion]
extended = true
min = "0.87.0"

[params]
descrition = "AlogZ, A Website for Blogs on A to Z Topics !"
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon/favicon.png"
DefaultContentLanguage = "en"

  [params.footer]
  customText = "AlogZ Media Group, All Rights Reserved. "

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 IST"

  [params.sidebar]
  compact = false
  emoji = "✅"
  subtitle = "A-Z Blogs"

    [params.sidebar.avatar]
    enabled = true
    local = false
    src = "/avatar/avatar.jpg"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false
  provider = "disqus"

    [params.comments.disqusjs]

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

    [params.comments.vssue]
    autoCreateIssue = false

    [params.comments.waline]
    emoji = [ "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo" ]
    requiredMeta = [ "name", "email", "url" ]

      [params.comments.waline.locale]
      admin = "Admin"

    [params.comments.twikoo]

    [params.comments.giscus]
    reactionsEnabled = 1
    emitMetadata = 0

    [params.comments.gitalk]

    [params.comments.cusdis]

  [params.widgets]
  homepage = [ ]
  page = [ ]

[params.opengraph.twitter]
card = "summary"

[params.defaultImage.opengraph]
enabled = true
local = false
src = "/defaultimage/opengraph.png"

  [params.colorScheme]
  toggle = false
  default = "dark"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true